name: "first"

on:
  push:
    branches:
      - develop
      - master
      - main

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step two
        uses: actions/checkout@v2
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort
  depends:
    name: Depending job
    needs: [job1,job2,job3]
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort